input_data_path: "../dataset/heart.csv"
output_model_path: "../models/model.pkl"
metric_path: "../models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
  model_params: {'n_estimators': 500, 'max_depth': 6}
  random_state: 42
feature_params:
  categorical_features:
    - 'sex' 
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal' 
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'   
  features_to_drop:
    - 'fbs'
    - 'chol'
    - 'trestbps'
    - 'age'
    - 'sex'
    - 'thal'
    - 'ca'
    - 'oldpeak'
    - 'exang'    
  target_col: 'target'

