apiVersion: v1
kind: Pod

metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: greasygoose/online_inference:v2
      name: online-inference
#      command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
      ports:
      - name: probe-port
        containerPort: 8000
        hostPort: 8000
        protocol: TCP
      resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
      livenessProbe:
        httpGet:
          path: /health
          port: probe-port
        initialDelaySeconds: 60
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health
          port: probe-port
        initialDelaySeconds: 5
        periodSeconds: 3